# Generated by Django 5.1.6 on 2025-03-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Batch',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Roll_Number',
            new_name='roll_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Semester',
            new_name='semester',
        ),
    ]
