# Generated by Django 5.1.6 on 2025-03-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_batch_student_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='batch',
            new_name='Batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='Roll_Number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='semester',
            new_name='Semester',
        ),
    ]
